apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: voting-app-dev

namespace: voting-app-dev

resources:
  - ../../base

commonLabels:
  environment: dev

patches:
  - path: patch-replicas.yaml
  - path: patch-ingress.yaml

images:
  - name: vote
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/vote
    newTag: 51b7864-20260127030854
  - name: result
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/result
    newTag: 51b7864-20260127030854
  - name: worker
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/worker
    newTag: 51b7864-20260127030854
