# Separate ingress for result app with path rewrite
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting-app-result
  labels:
    environment: dev
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - opsera-voting-app-dev.agent.opsera.dev
    secretName: voting-app-dev-tls
  rules:
  - host: opsera-voting-app-dev.agent.opsera.dev
    http:
      paths:
      - path: /results(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: result
            port:
              number: 80
