apiVersion: v1
kind: Namespace
metadata:
  name: voting-app-enterprise-2-dev
  labels:
    app.kubernetes.io/name: voting-app-enterprise-2
    app.kubernetes.io/managed-by: argocd
    environment: dev
